title: "【Go】Webフレームワークなしで開発する TODO API ハンズオン"
summary: |-
  このハンズオンでは、GoのWebフレームワークを使用せずに認証付きTodoアプリのAPIを開発していきます。
  また、このAPIのアーキテクチャには、クリーンアーキテクチャやドメイン駆動設計の考えを適用させています。

  マニアックな技術は特に扱っておらず、初学者の方が基本的なAPI開発を体験するためのハンズオンとなっています。反対に、すでにGoでの開発に慣れ親しんでいる方であれば本ハンズオンで得られるものは少ないかもしれません。

  アーキテクチャや設計手法、テスト、開発環境、認証、ORM....など色々な技術を網羅しています。また、概念や使用技術の説明に加え、公式ドキュメントや参考になる記事も逐一掲載しているので、つまづくことなくハンズオンを進められるように書いているつもりです。

  このハンズオンでは、以下のような技術を扱います。

  ・Docker,Docker composeによる環境構築
  ・GithubActionsを用いたCI
  ・クリーンアーキテクチャ
  ・ドメイン駆動設計
  ・モックを用いた単体テスト
  ・golang-migrate（DBマイグレーション）
  ・sqlc(ORM)
  ・JWT,Redisを用いた認証・認可
  ・net/http(標準パッケージ)
  ・swaggoを用いたAPIドキュメント生成
  ・ミドルウェア
  ・エンドポイントの統合テスト
  ・ゴールデンテスト

  【対象者】
  ・Goの文法をある程度知っている方
  ・Goを用いた開発の初学者の方
topics:
  - "go"
  - "api"
  - "アーキテクチャ"
  - "ハンズオン"
  - "todoアプリ"
published: true
price: 0
toc_depth: 2
chapters:
  - "01a18c"
  - "16108e"
  - "5fa7e2"
  - "4c8af0"
  - "724582"
  - "3cb4f6"
  - "e47dd1"
  - "4f098d"
  - "b23d35"
  - "d17416"
  - "7db743"
  - "d0c4cd"
  - "508eb5"
  - "63eff6"
  - "23f80a"
  - "af4e30"
allow_override: true
