title: "理解して構築してデプロイするまでやるインフラハンズオン"
summary: |-
  インフラ関連の技術は、アプリケーションレイヤーを主に触ってきた人からすると「わからんから手をつけられない」と苦手意識を持ってしまいがちだと思います。
  筆者もそのうちの一人です。

  おそらくこの辺は、実際に「構築」してみたほうがいいと思います。

  この書籍では、よく利用されるインフラ技術を用いてアプリケーションをデプロイしていきます。

  コンテナやk8s等の仕様について説明した後、コードを記述して動かすという流れでやっていきます。

  ⚠️ AWSリソースを利用する都合上、料金が発生します。

  キーワード：
  ・AWS
  ・Kubernetes
  ・IaC
  ・Terraform
  ・Docker
topics:
  - "aws"
  - "docker"
  - "kubernetes"
  - "インフラ"
  - "コンテナ"
published: true
price: 0
toc_depth: 3
chapters:
  - "692bdf"
  - "1d1124"
  - "043909"
  - "3f7076"
  - "d894c5"
  - "b791ec"
  - "da06be"
  - "1c35d3"

allow_override: true
